name: pandas-workshop
channels:
    - conda-forge
    - bioconda
dependencies:
  - python=3.11
  - pip
  - pip:
    - matplotlib
    - numpy
    - numexpr
    - pandas
    - scipy
    - seaborn
    - ipykernel
    - jupyterlab
